---
title: "Ordination Analysis"
author: "Mallarie Yeager"
date: "2024-09-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load libraries and data
```{r}
library(readxl)
library(readr)
library(RColorBrewer)
library(vegan)
library(FD)
library(ggplot2)
library(patchwork)
library(tidyverse)
library(ggplot2)
library(PNWColors)

here::here()
#load data
FT_comm_df <- read.csv("Ordination Analyses/Data/FT_community_df.csv")
comm.df <- read.csv("Ordination Analyses/Data/com.dat.fish.csv")
#set color pal
wes_palettes <- list(
  Darjeeling1 = c("#FF0000", "#00A08A", "#F2AD00", "#F98400", "#5BBCD6"),
  Cavalcanti1 = c("#D8B70A", "#02401B", "#A2A475", "#81A88D", "#972D15"),
  GrandBudapest1 = c("#F1BB7B", "#FD6467", "#5B1A18", "#D67236")
)

ponds <- c("NP","PP","PJ","WP", "GH","QP")
pal <- data.frame(Pond = ponds,col = c(wes_palettes$Darjeeling1[1], 
                                        wes_palettes$Darjeeling1[2], 
                                        wes_palettes$Darjeeling1[5],
                                        wes_palettes$Darjeeling1[4], 
                                        wes_palettes$Cavalcanti1[1],
                                        wes_palettes$GrandBudapest1[3]))
```
Clean community df 

```{r}

##Calculate stats on how well we sampled the community
#sum by Common_name
sum.fish.total <- aggregate(FREQ ~ Common_name, data = comm.df, sum)
#sum com matrix based on FT
sum.fish.FT <- aggregate(FREQ ~ Common_name, data = FT_comm_df, sum)
#find proportion of abundance used to the total survey
sum(sum.fish.FT[,2])/sum(sum.fish.total[,2])

sum.fish.all <- merge(sum.fish.total, sum.fish.FT, by = "Common_name", all = T)
sum.fish.all[is.na(sum.fish.all)] <- 0
sum.fish.all$prop <- sum.fish.all[,2]-sum.fish.all[,3]
(1-778/sum(sum.fish.total[,2]))



#make anything >1,000 == 1,000, while retaining size structure
#QP14-Menhaden
#tmp <- subset(FT_comm_df, Station == "QP1" & Year == "2014" & Common_name == "Atlantic Menhaden")
#FT_comm_df[rownames(tmp),8] <- tmp$FREQ * 1000/sum(tmp$FREQ)
#GH14-Silverside
#tmp <- subset(FT_comm_df, Station == "GH1" & Year == "2014" & Common_name == "Atlantic Silverside")
#FT_comm_df[rownames(tmp),8] <- tmp$FREQ * 1000/sum(tmp$FREQ)
#PP15-Menhaden
#tmp <- subset(FT_comm_df, Station == "PP1" & Year == "2015" & Common_name == "Atlantic Menhaden")
#FT_comm_df[rownames(tmp),8] <- tmp$FREQ * 1000/sum(tmp$FREQ)
#NP14-Silverside
#tmp <- subset(FT_comm_df, Station == "NP3" & Year == "2014" & Common_name == "Atlantic Silverside")
#FT_comm_df[rownames(tmp),8] <- tmp$FREQ * 1000/sum(tmp$FREQ)
#NP10-Silverside
#tmp <- subset(FT_comm_df, Station == "NP4" & Year == "2010" & Common_name == "Atlantic Silverside")
#FT_comm_df[rownames(tmp),8] <- tmp$FREQ * 1000/sum(tmp$FREQ)
#PJ15-Silverside
#tmp <- subset(FT_comm_df, Station == "PJ1" & Year == "2015" & Common_name == "Atlantic Silverside")

FT_comm_df$FL <- round(FT_comm_df$FL) #rounds forklength


FT.mat1  <- FT_comm_df[!duplicated(FT_comm_df[,c(2,8)]),] #removes duplicates of spc*size combo
FT.mat1 <- FT.mat1[order(FT.mat1$FL),] #reorders matrix by FL 
FT.mat1 <- FT.mat1[order(FT.mat1$Common_name),] #then Common name

FT.mat <- as.data.frame(FT.mat1[,c(11:23)]) #Creates trait matrix with spc*size row names
rownames(FT.mat) <- paste(FT.mat1$Common_name, FT.mat1$FL) #creates rownames
sapply(FT.mat[,1:13], FUN = min) #checks to make sure FTs are not negative

#Abundance Matrix
fish.freq <- aggregate(FREQ ~ Common_name + FL + Pond + Year, data = FT_comm_df, sum) #sums freq up for all spc * size combos
fish.freq <- fish.freq[order(fish.freq$FL),] #reorders matrix by FL 
fish.freq <- fish.freq[order(fish.freq$Common_name),] #then Common name
fish.freq$spc_fl <- paste(fish.freq$Common_name, fish.freq$FL) #creates a species x length column
fish.freq <- fish.freq[,-c(1:2)] #removes common name and length cols
abund <- reshape(fish.freq, timevar = "spc_fl" , idvar = c("Pond", "Year"), direction = "wide") #reshapes data to wide format - spc*size on cols
abund.mat <- abund[,-c(1:2)] #removes pond and year columns
row.names(abund.mat) <- paste(abund$Pond, abund$Year) #creates rownames
names(abund.mat) <- substring(names(abund.mat), 6) #cleans up col names
abund.mat[is.na(abund.mat)] <- 0 #places zeros were NAs were

#FT and Abundance Check#
check <- cbind(rownames(FT.mat), colnames(abund.mat)) #checks to make sure FT rownames and abund colnames match

```
Calculate CWM FD
```{r Run CWM}
set.seed(12)
FD.test <- FD::functcomp(x = as.matrix(FT.mat[,1:13]), a = as.matrix(abund.mat))
```

##Run Ordination on FT community data

```{r Measuring FT relative distance }
#Plotting CWM in ordination space
#FT
FT.sums <- FD.test
FT.sums$yr_pd <- rownames(FD.test)
FT.sums$Pond <- substr(FT.sums$yr_pd, 1, 2)
FT.sums$Year <- substr(FT.sums$yr_pd, 4, 7)
#FT.sums <- FT.sums[,c(14:15,1:12)]
FT.sums <- FT.sums[,c(15:16,1:13)]
#write_csv(FT.sums, "CWM.df.csv")
FT.sums <- FT.sums[order(FT.sums$Year),]
FT.sums <- FT.sums[order(FT.sums$Pond),]
#write.csv(FT.sums, "/Users/mallarie.yeager/My Documents/R_projects/FT Stability/Ordination Analyses/Outputs/Functional_trait_comm_dat.csv", row.names = F)
set.seed(12)
FT.mds <- metaMDS(FT.sums[,3:ncol(FT.sums)], k = 2, trymax = 10000, maxit = 10000)
coords <- as.data.frame(FT.mds$points)
coords <- cbind(FT.sums[,1:2], coords)
coords <- merge(coords, pal, by = "Pond")
#png("/Users/mallarie.yeager/Documents/R_projects/FT Stability/Ordination Analyses/Plots/Functional_trait_yr_cent.png", width =8, height = 8, units = "in", res = 300)

plot(coords$MDS1, coords$MDS2,  type = "n", xlab = "nMDS1", ylab = "nMDS2",xlim = c(-0.4,0.25), ylim = c(-0.25,0.25), cex = 1.5)
abline(h = 0, lty = 2)
abline(v = 0, lty = 2)
#text(col.FT$MDS1, col.FT$MDS2, labels = col.FT$FT, col = as.character(col.FT$col), cex = 1.5)
#orditorp(FT.mds, display = "species", air = 0.01, cex = 1, col = "grey")
for (i in 1:nrow(coords)) {
  text(coords$MDS1[i], coords$MDS2[i], 
       labels = substr(as.character(coords$Year[i]), 
                       start = 3, stop = 4),
       col = c(as.character(coords$col[i])),
       pos = 1, cex = 1.5)
}

#dev.off()
#plot(FT.fit, col= c("grey","black","grey","black","grey","black","grey","grey","darkgrey","grey","grey","grey","grey","grey","black","black","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey"))
NP.e.F <- ordiellipse(FT.mds, kind = "se", groups = FT.sums$Pond, show = "NP", lwd = 2, col = as.character(coords$col[coords$Pond == "NP"]))
PP.e.F <- ordiellipse(FT.mds, kind = "se",groups = FT.sums$Pond, show = "PP", lwd = 2, col = as.character(coords$col[coords$Pond == "PP"]))
PJ.e.F <- ordiellipse(FT.mds, kind = "se",groups = FT.sums$Pond, show = "PJ", lwd = 2, col = as.character(coords$col[coords$Pond == "PJ"]))
WP.e.F <- ordiellipse(FT.mds, kind = "se",groups = FT.sums$Pond, show = "WP", lwd = 2, col= as.character(coords$col[coords$Pond == "WP"]))
GH.e.F <- ordiellipse(FT.mds, kind = "se",groups = FT.sums$Pond, show = "GH", lwd = 2, col = as.character(coords$col[coords$Pond == "GH"]))
QP.e.F <- ordiellipse(FT.mds, kind = "se", groups = FT.sums$Pond, show = "QP", lwd = 2, col = as.character(coords$col[coords$Pond == "QP"]))
legend("topright", legend = c("NP", "PP", "PJ", "WP", "GH", "QP"),
       col = as.character(pal$col), ncol = 2, lwd = 2, lty = 1, bty = "n")
#plot(FT.fit)
coords$MDS1centroid[coords$Pond == "NP"] <- NP.e.F$NP$center[1]
coords$MDS2centroid[coords$Pond == "NP"] <- NP.e.F$NP$center[2]
coords$MDS1centroid[coords$Pond == "PP"] <- PP.e.F$PP$center[1]
coords$MDS2centroid[coords$Pond == "PP"] <- PP.e.F$PP$center[2]
coords$MDS1centroid[coords$Pond == "QP"] <- QP.e.F$QP$center[1]
coords$MDS2centroid[coords$Pond == "QP"] <- QP.e.F$QP$center[2]
coords$MDS1centroid[coords$Pond == "WP"] <- WP.e.F$WP$center[1]
coords$MDS2centroid[coords$Pond == "WP"] <- WP.e.F$WP$center[2]
coords$MDS1centroid[coords$Pond == "PJ"] <- PJ.e.F$PJ$center[1]
coords$MDS2centroid[coords$Pond == "PJ"] <- PJ.e.F$PJ$center[2]
coords$MDS1centroid[coords$Pond == "GH"] <- GH.e.F$GH$center[1]
coords$MDS2centroid[coords$Pond == "GH"] <- GH.e.F$GH$center[2]

plot(coords$MDS1, coords$MDS2,  type = "n", xlab = "nMDS1",  ylab = "nMDS2",xlim = c(-0.4,0.4), ylim = c(-0.4,0.4))
abline(h = 0, lty = 2)
abline(v = 0, lty = 2)
for (i in 1:nrow(coords)) {
  text(coords$MDS1[i], coords$MDS2[i], 
       labels = substr(as.character(coords$Year[i]), 
                       start = 3, stop = 4),
       col = c(as.character(coords$col[i])),
       pos = 1, cex = 0.75)
}
points(NP.e.F$NP$center[1], NP.e.F$NP$center[2], col = as.character(pal$col[pal$Pond == "NP"]), pch = 16)
points(PP.e.F$PP$center[1], PP.e.F$PP$center[2], col = as.character(pal$col[pal$Pond == "PP"]), pch = 16)
points(QP.e.F$QP$center[1], QP.e.F$QP$center[2], col = as.character(pal$col[pal$Pond == "QP"]), pch = 16)
points(PJ.e.F$PJ$center[1], PJ.e.F$PJ$center[2], col = as.character(pal$col[pal$Pond == "PJ"]), pch = 16)
points(GH.e.F$GH$center[1], GH.e.F$GH$center[2], col = as.character(pal$col[pal$Pond == "GH"]), pch = 16)
points(WP.e.F$WP$center[1], WP.e.F$WP$center[2], col = as.character(pal$col[pal$Pond == "WP"]), pch = 16)
for (j in 1:length(ponds)) {
  s <- subset(coords, Pond == ponds[j])
  s <- s[order(s$Year), ]
  #points(s$MDS1, s$MDS2, pch = 21, col = as.character(s$col[1]), bg = s$col[1], cex = 0.5)
  for (k in 1:(nrow(s))) {
    arrows(x0 = s$MDS1[k], y0 = s$MDS2[k],
           x1 = s$MDS1centroid[k], y1 =s$MDS2centroid[k] ,
           code = 1, col = as.character(s$col[k]), len = 0)
  }
}
legend("topright", legend = c("GH", "NP","PJ", "PP", "QP", "WP"),
       col = as.character(pal$col), ncol = 2, lwd = 2, lty = 1, bty = "n")

plot(coords$MDS1, coords$MDS2,  type = "n", xlab = "nMDS1" ,ylab = "nMDS2",xlim = c(-0.4,0.4), ylim = c(-0.4,0.4))
abline(h = 0, lty = 2)
abline(v = 0, lty = 2)
for (i in 1:nrow(coords)) {
  text(coords$MDS1[i], coords$MDS2[i], 
       labels = substr(as.character(coords$Year[i]), 
                       start = 3, stop = 4),
       col = c(as.character(coords$col[i])),
       pos = 1, cex = 0.75)
}
for (j in 1:length(ponds)) {
  s <- subset(coords, Pond == ponds[j])
  s <- s[order(s$Year), ]
  points(s$MDS1, s$MDS2, pch = 21, col = as.character(s$col[1]), bg = s$col[1], cex = 0.5)
  for (k in 1:(nrow(s) - 1)) {
    arrows(x0 = s$MDS1[k], y0 = s$MDS2[k],
           x1 = s$MDS1[k+1], y1 = s$MDS2[k+1],
           code = 2, col = as.character(s$col[k]), len = 0.1)
  }
}

legend("topright", legend = pal$Pond,
       col = as.character(pal$col), ncol = 2, lwd = 2, lty = 1, bty = "n")

coord.FT.cent <- coords
coord.FT.cent <- coord.FT.cent[order(coord.FT.cent$Year),]
coord.FT.cent <- coord.FT.cent[order(coord.FT.cent$Pond),]
coord.FT.cent <- coord.FT.cent[,c(1:4,6:7,5)]
```
##Run Ordination on species community data
```{r Measuring community relative distance}
#Community comp
avg.by.year <- aggregate(FREQ ~ Pond + Year + Common_name, FUN = mean, data = FT_comm_df)
sums.3 <- reshape(avg.by.year, timevar = c("Common_name"), ids = c(FREQ), idvar = c("Pond","Year"), direction = "wide")
sums.2 <- sums.3[,3:ncol(sums.3)]
#removes the "FREQ." before each name
names(sums.2) <- substring(names(sums.2), 6)
#replaces NA's with 0's
sums.2[is.na(sums.2)] <- 0
#sums.1 <- decostand(sums.2[,9:ncol(sums.2)], method = "hellinger")
sums <- cbind(sums.3[,1:2], sums.2)
sums <- sums[order(sums$Year),]
sums <- sums[order(sums$Pond),]
#write.csv(sums, "/Users/mallarie.yeager/My Documents/R_projects/FT Stability/Ordination Analyses/Outputs/Species_comm_dat.csv", row.names = F)
set.seed(12)
com.mds <- metaMDS(sums[,3:ncol(sums)],k=2, trymax = 10000, maxit = 10000)
coords.com.cent <- as.data.frame(com.mds$points)
coords.com.cent$Pond <- sums$Pond
coords.com.cent$Year <- sums$Year
coords.com.cent <- merge(coords.com.cent, pal, by = "Pond")
#png("/Users/mallarie.yeager/Documents/R_projects/FT Stability/Ordination Analyses/Plots/Species_nmds_yr_yr.png", width =8, height = 8, units = "in", res = 300)

plot(coords.com.cent$MDS1, coords.com.cent$MDS2,  type = "n", xlab = "nMDS1", xlim = c(-1,0.7), ylim = c(-0.7,0.7), ylab = "nMDS2")
abline(h = 0, lty = 2)
abline(v = 0, lty = 2)
#text(col.com$MDS1, col.com$MDS2, labels = col.com$Common_name, col = as.character(col.com$col))
#orditorp(com.mds, display = "species", air = 0.01, cex = 1, col = "grey")
for (i in 1:nrow(coords.com.cent)) {
  text(coords.com.cent$MDS1[i], coords.com.cent$MDS2[i], 
       labels = substr(as.character(coords.com.cent$Year[i]), 
                       start = 3, stop = 4),
       col = c(as.character(coords.com.cent$col[i])),
       pos = 1, cex = 1.5)
}
#dev.off()
#plot(com.fit, col = c("grey","black","grey","grey","grey","black","grey","grey","black","grey","grey","black","grey" ))
NP.e.C <- ordiellipse(com.mds, kind = "se", groups = sums$Pond, show = "NP", lwd = 2, col = as.character(coords.com.cent$col[coords.com.cent$Pond == "NP"]))
PP.e.C <- ordiellipse(com.mds, kind = "se",groups = sums$Pond, show = "PP", lwd = 2, col = as.character(coords.com.cent$col[coords.com.cent$Pond == "PP"]))
PJ.e.C <- ordiellipse(com.mds, kind = "se",groups = sums$Pond, show = "PJ", lwd = 2, col = as.character(coords.com.cent$col[coords.com.cent$Pond == "PJ"]))
WP.e.C <- ordiellipse(com.mds, kind = "se",groups = sums$Pond, show = "WP", lwd = 2, col= as.character(coords.com.cent$col[coords.com.cent$Pond == "WP"]))
GH.e.C <- ordiellipse(com.mds, kind = "se",groups = sums$Pond, show = "GH", lwd = 2, col = as.character(coords.com.cent$col[coords.com.cent$Pond == "GH"]))
QP.e.C <- ordiellipse(com.mds, kind = "se", groups = sums$Pond, show = "QP", lwd = 2, col = as.character(coords.com.cent$col[coords.com.cent$Pond == "QP"]))
legend("topright", legend = c("NP", "PP", "PJ", "WP", "GH", "QP"),
       col = as.character(pal$col), ncol = 2, lwd = 2, lty = 1, bty = "n")

coords.com.cent$MDS1centroid[coords.com.cent$Pond == "NP"] <- NP.e.C$NP$center[1]
coords.com.cent$MDS2centroid[coords.com.cent$Pond == "NP"] <- NP.e.C$NP$center[2]
coords.com.cent$MDS1centroid[coords.com.cent$Pond == "PP"] <- PP.e.C$PP$center[1]
coords.com.cent$MDS2centroid[coords.com.cent$Pond == "PP"] <- PP.e.C$PP$center[2]
coords.com.cent$MDS1centroid[coords.com.cent$Pond == "QP"] <- QP.e.C$QP$center[1]
coords.com.cent$MDS2centroid[coords.com.cent$Pond == "QP"] <- QP.e.C$QP$center[2]
coords.com.cent$MDS1centroid[coords.com.cent$Pond == "WP"] <- WP.e.C$WP$center[1]
coords.com.cent$MDS2centroid[coords.com.cent$Pond == "WP"] <- WP.e.C$WP$center[2]
coords.com.cent$MDS1centroid[coords.com.cent$Pond == "PJ"] <- PJ.e.C$PJ$center[1]
coords.com.cent$MDS2centroid[coords.com.cent$Pond == "PJ"] <- PJ.e.C$PJ$center[2]
coords.com.cent$MDS1centroid[coords.com.cent$Pond == "GH"] <- GH.e.C$GH$center[1]
coords.com.cent$MDS2centroid[coords.com.cent$Pond == "GH"] <- GH.e.C$GH$center[2]

plot(coords.com.cent$MDS1, coords.com.cent$MDS2,  type = "n", xlab = "nMDS1", xlim =  c(-1.1,0.7), ylim = c(-0.7,0.7), ylab = "nMDS2")
abline(h = 0, lty = 2)
abline(v = 0, lty = 2)
for (i in 1:nrow(coords.com.cent)) {
  text(coords.com.cent$MDS1[i], coords.com.cent$MDS2[i], 
       labels = substr(as.character(coords.com.cent$Year[i]), 
                       start = 3, stop = 4),
       col = c(as.character(coords.com.cent$col[i])),
       pos = 1, cex = 0.75)
}
points(NP.e.C$NP$center[1], NP.e.C$NP$center[2], col = as.character(pal$col[pal$Pond == "NP"]), pch = 16)
points(PP.e.C$PP$center[1], PP.e.C$PP$center[2], col = as.character(pal$col[pal$Pond == "PP"]), pch = 16)
points(QP.e.C$QP$center[1], QP.e.C$QP$center[2], col = as.character(pal$col[pal$Pond == "QP"]), pch = 16)
points(PJ.e.C$PJ$center[1], PJ.e.C$PJ$center[2], col = as.character(pal$col[pal$Pond == "PJ"]), pch = 16)
points(GH.e.C$GH$center[1], GH.e.C$GH$center[2], col = as.character(pal$col[pal$Pond == "GH"]), pch = 16)
points(WP.e.C$WP$center[1], WP.e.C$WP$center[2], col = as.character(pal$col[pal$Pond == "WP"]), pch = 16)
for (j in 1:length(ponds)) {
  
  s <- subset(coords.com.cent, Pond == ponds[j])
  s <- s[order(s$Year), ]
  #points(s$MDS1, s$MDS2, pch = 21, col = as.character(s$col[1]), bg = s$col[1], cex = 0.5)
  for (k in 1:(nrow(s))) {
    arrows(x0 = s$MDS1[k], y0 = s$MDS2[k],
           x1 = s$MDS1centroid[k], y1 =s$MDS2centroid[k] ,
           code = 1, col = as.character(s$col[k]), len = 0)
  }
}
legend("bottomright", legend = c("NP", "PP", "PJ", "WP", "GH", "QP"),
       col = as.character(pal$col), ncol = 2, lwd = 2, lty = 1, bty = "n")

plot(coords.com.cent$MDS1, coords.com.cent$MDS2,  type = "n", xlab = "nMDS1", xlim =  c(-1.1,0.7), ylim = c(-0.7,0.7), ylab = "nMDS2")
abline(h = 0, lty = 2)
abline(v = 0, lty = 2)
for (i in 1:nrow(coords.com.cent)) {
  text(coords.com.cent$MDS1[i], coords.com.cent$MDS2[i], 
       labels = substr(as.character(coords.com.cent$Year[i]), 
                       start = 3, stop = 4),
       col = c(as.character(coords.com.cent$col[i])),
       pos = 1, cex = 0.75)
}
for (j in 1:length(ponds)) {
  s <- subset(coords.com.cent, Pond == ponds[j])
  s <- s[order(s$Year), ]
  points(s$MDS1, s$MDS2, pch = 21, col = as.character(s$col[1]), bg = s$col[1], cex = 0.5)
  for (k in 1:(nrow(s) - 1)) {
    arrows(x0 = s$MDS1[k], y0 = s$MDS2[k],
           x1 = s$MDS1[k+1], y1 = s$MDS2[k+1],
           code = 2, col = as.character(s$col[k]), len = 0.1)
  }
}
legend("topright", legend = c("GH", "NP","PJ", "PP", "QP", "WP"),
       col = as.character(pal$col), ncol = 2, lwd = 2, lty = 1, bty = "n")


coords.com.cent <- coords.com.cent[order(coords.com.cent$Year),]
coords.com.cent <- coords.com.cent[order(coords.com.cent$Pond),]
coords.com.cent <- coords.com.cent[,c(1,4,2:3,6:7,5)]
```

